<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Employees\GetEmployeesForSelection\**" />
    <EmbeddedResource Remove="Features\Employees\GetEmployeesForSelection\**" />
    <None Remove="Features\Employees\GetEmployeesForSelection\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRMS.Domain\HRMS.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\WorkSchedule\CreateWorkSchedule\" />
  </ItemGroup>

</Project>
